import { sql } from "drizzle-orm";
import { logger } from "../logger.js";
import { kalshiFetch } from "../kalshi.js";
const ETH_15M_MS=15*60_000, WRITE_REFRESH_MS=60_000, SCHEMA_LOCK=42015001;
export interface EthSignalEvidenceInput { serviceRole:string; ticker:string; marketOpenTimeMs:number|null; observedAtMs:number; currentFloorStrike?:number|null; priorFloorStrike?:number|null; currentMove?:number|null; direction?:string|null; p80?:number|null; p90?:number|null; p95?:number|null; p99?:number|null; sampleCount?:number|null; rejectionReason?:string|null; outcome?:string|null; evidence?:Record<string,unknown>; }
let initPromise:Promise<void>|null=null; const lastFingerprint=new Map<string,string>(), lastWriteAt=new Map<string,number>();
function finiteOrNull(v:unknown){return typeof v==="number"&&Number.isFinite(v)?v:null;} function positiveStrike(raw:Record<string,unknown>|null|undefined){if(!raw)return null;const v=raw["floor_strike"]??raw["cap_strike"];const n=typeof v==="number"?v:typeof v==="string"&&v.trim()?Number(v):NaN;return Number.isFinite(n)&&n>0?n:null;} async function getDb(){const m=await import("@workspace/db");return m.db;}
async function ensureTable(){if(!initPromise){initPromise=(async()=>{const db=await getDb();await db.transaction(async tx=>{await tx.execute(sql`SELECT pg_advisory_xact_lock(${SCHEMA_LOCK})`);await tx.execute(sql`CREATE TABLE IF NOT EXISTS eth_signal_evidence_ledger (service_role text NOT NULL,ticker text NOT NULL,market_open_time_ms bigint NOT NULL,observed_at_ms bigint NOT NULL,current_floor_strike double precision,prior_floor_strike double precision,current_move double precision,direction text,p80 double precision,p90 double precision,p95 double precision,p99 double precision,sample_count integer,rejection_reason text,outcome text,evidence_json text NOT NULL DEFAULT '{}',updated_at_ms bigint NOT NULL,PRIMARY KEY(service_role,ticker))`);await tx.execute(sql`CREATE INDEX IF NOT EXISTS eth_signal_evidence_ledger_updated_idx ON eth_signal_evidence_ledger(updated_at_ms DESC)`);});})().catch(e=>{initPromise=null;throw e;});}return initPromise;}
async function enrich(input:EthSignalEvidenceInput){let current=finiteOrNull(input.currentFloorStrike),prior=finiteOrNull(input.priorFloorStrike);const open=input.marketOpenTimeMs;if(!Number.isInteger(open)||open!<=0||!/^KXETH15M-/.test(input.ticker))return{current,prior};try{if(current==null){const r=await kalshiFetch<{market?:Record<string,unknown>}>(`/markets/${input.ticker}`);const raw=r.market,ms=typeof raw?.["open_time"]==="string"?Date.parse(raw["open_time"] as string):NaN;if(ms===open)current=positiveStrike(raw);}if(prior==null){const target=open!-ETH_15M_MS;const r=await kalshiFetch<{markets?:Array<Record<string,unknown>>}>("/markets",{series_ticker:"KXETH15M",status:"settled",limit:100});const matches=(r.markets??[]).filter(row=>{const ms=typeof row["open_time"]==="string"?Date.parse(row["open_time"] as string):NaN;return ms===target&&typeof row["ticker"]==="string"&&/^KXETH15M-/.test(row["ticker"] as string);});const s=new Set(matches.map(positiveStrike).filter((v):v is number=>v!=null));if(s.size===1)prior=[...s][0]!;}}catch{}return{current,prior};}
async function persist(input:EthSignalEvidenceInput){if(!input.serviceRole||!/^KXETH15M-/.test(input.ticker))return;const open=input.marketOpenTimeMs;if(!Number.isInteger(open)||open!<=0)return;const key=`${input.serviceRole}:${input.ticker}`,fp=JSON.stringify({currentMove:finiteOrNull(input.currentMove),direction:input.direction??null,p80:finiteOrNull(input.p80),p90:finiteOrNull(input.p90),p95:finiteOrNull(input.p95),p99:finiteOrNull(input.p99),sampleCount:Number.isInteger(input.sampleCount)?input.sampleCount:null,rejectionReason:input.rejectionReason??null,outcome:input.outcome??null,evidence:input.evidence??{}}),now=Date.now();if(lastFingerprint.get(key)===fp&&now-(lastWriteAt.get(key)??0)<WRITE_REFRESH_MS)return;const s=await enrich(input);await ensureTable();const db=await getDb(),move=finiteOrNull(input.currentMove),p80=finiteOrNull(input.p80),p90=finiteOrNull(input.p90),p95=finiteOrNull(input.p95),p99=finiteOrNull(input.p99),count=Number.isInteger(input.sampleCount)?input.sampleCount!:null,dir=input.direction??null,reason=input.rejectionReason??null,outcome=input.outcome??null,evidence=JSON.stringify(input.evidence??{});await db.execute(sql`INSERT INTO eth_signal_evidence_ledger(service_role,ticker,market_open_time_ms,observed_at_ms,current_floor_strike,prior_floor_strike,current_move,direction,p80,p90,p95,p99,sample_count,rejection_reason,outcome,evidence_json,updated_at_ms) VALUES(${input.serviceRole},${input.ticker},${open!},${input.observedAtMs},${s.current},${s.prior},${move},${dir},${p80},${p90},${p95},${p99},${count},${reason},${outcome},${evidence},${now}) ON CONFLICT(service_role,ticker) DO UPDATE SET market_open_time_ms=EXCLUDED.market_open_time_ms,observed_at_ms=EXCLUDED.observed_at_ms,current_floor_strike=COALESCE(EXCLUDED.current_floor_strike,eth_signal_evidence_ledger.current_floor_strike),prior_floor_strike=COALESCE(EXCLUDED.prior_floor_strike,eth_signal_evidence_ledger.prior_floor_strike),current_move=EXCLUDED.current_move,direction=EXCLUDED.direction,p80=EXCLUDED.p80,p90=EXCLUDED.p90,p95=EXCLUDED.p95,p99=EXCLUDED.p99,sample_count=EXCLUDED.sample_count,rejection_reason=EXCLUDED.rejection_reason,outcome=EXCLUDED.outcome,evidence_json=EXCLUDED.evidence_json,updated_at_ms=EXCLUDED.updated_at_ms`);lastFingerprint.set(key,fp);lastWriteAt.set(key,now);logger.info({serviceRole:input.serviceRole,ticker:input.ticker},"ETH_SIGNAL_EVIDENCE_LEDGER_UPSERTED");}
export function scheduleEthSignalEvidence(input:EthSignalEvidenceInput){void persist(input).catch(err=>logger.warn({err,serviceRole:input.serviceRole,ticker:input.ticker},"ETH_SIGNAL_EVIDENCE_LEDGER_WRITE_FAILED"));}
